config:
  project_repos:
    onedataSim:
      repo: 'https://github.com/EOSC-synergy/onedataSim'
      branch: dev  # I'd like to be a variable i.e GIT_BRANCH
# I'd like to use DOCKERPASS as ONEDATA token...
#  credentials:
#    - id: onedataSim-dockerhub-xxx
#      username_var: JPL_DOCKERUSER
#      password_var: JPL_DOCKERPASS
# environment:
# #  JPL_DOCKERSERVER: "hub.docker.com"
#   JPL_DOCKERPUSH: "onedataSim"
#   JPL_DOCKERFORCEBUILD: "True"
# #  LANG: C.UTF-8

sqa_criteria:
  qc_style:
    repos:
      onedataSim:
        container: onedataSim-testing
        commands:
          # "Flake 8 is the wrapper which verifies pep8, pyflakes and circular complexity"
          # "The error code of flake8 are E***, W*** used in pep8 and F*** and C9**"   
          #  Alternative: hacking is a flake8' plug-in, based on OpenStack OpenStack Style Guidlines, 
          #               which are based on Google Python Style Guide.
          - flake8
  qc_coverage:
    repos:
      onedataSim:
        container: onedataSim-testing
        commands: 
          - cover
  qc_functional:
    repos:
      onedataSim:
        # we need a complete build to test simulations
        container: onedataSim-build   
        commands:
          - unittest
  qc_security:
    repos:
      onedataSim:
        container: onedataSim-testing
        commands: 
          - bandit
  qc_doc:
    repos:
      onedataSim:
        container: onedataSim-testing
        commands:
          - python setup.py build_sphinx

timeout: 900
