version: "3.6"

services:
  onedatasim-testing:
    image: "indigodatacloud/ci-images:python3.6"
    container_name: "onedatasim-testing"
    volumes:
     - type: bind
       source: ./onedatasim
       target: /onedatasim-repo
    #command: sleep 3600

# Temporaly disabled due to onedata token
  onedatasim-build:
    build:
      context: "."
      dockerfile: "./Dockerfile"
      args:
        ONECLIENT_ACCESS_TOKEN_TO_BUILD : "MDAxY2xvY2F00aW9uIGRhdGFodWIuZWdpLmV1CjAwNmJpZGVudGlmaWVyIDIvbm1kL3Vzci005NDJiOTYwZTBlN2RkMzhiNzI3M2JiMzVkMDMwNzYxMWNoN2RkMy9hY3QvMDkwNzc00MGJmZTU00OWE3NWFlMTE4NDI2ZmE1Y2JlMDRjaDdlZmEKMDAxNmNpZCBkYXRhLnJlYWRvbmx5CjAwNDljaWQgZGF00YS5wYXRoID00gTDJOaE5UVTVPRFExT1RZeVpEY3hPR1EwTUdJeE5UbGhORGM00TnpGbU1UTTVZMmcxTVRZeAowMDJmc2lnbmF00dXJlINfeoejWH5udS67x93CZkDdxFZaf1HKWGIDAE8HOwsqECg"
        ONECLIENT_PROVIDER_HOST_TO_BUILD : "https://mon01-tic.ciemat.es"
#   #image: "lagoproject/onedatasim:latest" # image could be at DockerHub (under consideration)
#   #command: sleep 3600
